import type { ForgeConfig } from '@electron-forge/shared-types';
import { MakerSquirrel } from '@electron-forge/maker-squirrel';
import { MakerZIP } from '@electron-forge/maker-zip';
import { MakerDeb } from '@electron-forge/maker-deb';
import { MakerRpm } from '@electron-forge/maker-rpm';
// import { MakerFlatpak } from '@electron-forge/maker-flatpak';
import { PublisherGithub } from '@electron-forge/publisher-github';
import { AutoUnpackNativesPlugin } from '@electron-forge/plugin-auto-unpack-natives';
import { VitePlugin } from '@electron-forge/plugin-vite';
import { FusesPlugin } from '@electron-forge/plugin-fuses';
import { FuseV1Options, FuseVersion } from '@electron/fuses';
import * as fs from 'fs';
import * as path from 'path';

// if (process.env.APPLE_ID && process.env.APPLE_PASSWORD && process.env.APPLE_TEAM_ID) {

const config: ForgeConfig = {
    packagerConfig: {
        asar: {
            // Unpack .node binaries so dlopen/Node addon loader can find them
            // on the filesystem, plus the matching debug-info bundles so
            // std::backtrace can resolve file:line for production panic logs:
            //   - macOS:   `<name>.node.dSYM/...` (lookup by co-location)
            //   - Windows: `<name>.node.pdb`     (lookup by co-location)
            //   - Linux:   embedded in the `.node`, nothing extra to unpack.
            unpack: '**/*.{node,node.pdb,dSYM,dSYM/**}',
        },
        executableName: 'Operator',
        extendInfo: {
            NSLocalNetworkUsageDescription:
                'Operator uses the local network to sync tempo with other music apps via Ableton Link.',
            NSBonjourServices: ['_SessionStatus._tcp'],
        },
        osxSign: {
            identity: 'Developer ID Application: Daniel Lewis (HA98TTLCR7)',
            optionsForFile: () => {
                return {
                    hardenedRuntime: true,
                    entitlements: 'entitlements.plist',
                    'entitlements-inherit': 'entitlements.plist',
                    signatureFlags: 'library',
                };
            },
        },

        // macOS notarization configuration
        // Only runs when environment variables are present (i.e., in CI)
        osxNotarize:
            process.env.APPLE_ID &&
            process.env.APPLE_PASSWORD &&
            process.env.APPLE_TEAM_ID
                ? {
                      appleId: process.env.APPLE_ID,
                      appleIdPassword: process.env.APPLE_PASSWORD,
                      teamId: process.env.APPLE_TEAM_ID,
                  }
                : undefined,
    },
    rebuildConfig: {},
    hooks: {
        // Copy @modular/core workspace package to node_modules before packaging
        // This is needed because yarn workspaces use symlinks which don't survive packaging
        packageAfterCopy: async (_config, buildPath) => {
            const sourceDir = path.join(__dirname, 'crates', 'modular');
            const targetDir = path.join(
                buildPath,
                'node_modules',
                '@modular',
                'core',
            );

            // Ensure target directory exists
            fs.mkdirSync(targetDir, { recursive: true });

            // Files to copy from the native module package
            const filesToCopy = ['index.js', 'index.d.ts', 'package.json'];

            for (const file of filesToCopy) {
                const src = path.join(sourceDir, file);
                const dest = path.join(targetDir, file);
                if (fs.existsSync(src)) {
                    fs.copyFileSync(src, dest);
                }
            }

            // Copy the native .node file for the current platform
            const nodeFiles = fs
                .readdirSync(sourceDir)
                .filter((f) => f.endsWith('.node'));
            for (const nodeFile of nodeFiles) {
                fs.copyFileSync(
                    path.join(sourceDir, nodeFile),
                    path.join(targetDir, nodeFile),
                );
                // Copy the platform-specific debug-info bundle next to the
                // .node so std::backtrace resolves file:line in production
                // panic logs. Bundles are generated by
                // `scripts/copy-debuginfo.mjs` after `napi build`.
                //   - macOS:   <name>.node.dSYM (directory)
                //   - Windows: <name>.node.pdb  (file)
                //   - Linux:   no extra file; DWARF is in the .node already.
                const dsymSrc = path.join(sourceDir, `${nodeFile}.dSYM`);
                if (fs.existsSync(dsymSrc)) {
                    fs.cpSync(
                        dsymSrc,
                        path.join(targetDir, `${nodeFile}.dSYM`),
                        { recursive: true, dereference: true },
                    );
                }
                const pdbSrc = path.join(sourceDir, `${nodeFile}.pdb`);
                if (fs.existsSync(pdbSrc)) {
                    fs.copyFileSync(
                        pdbSrc,
                        path.join(targetDir, `${nodeFile}.pdb`),
                    );
                }
            }
        },
    },
    makers: [
        new MakerSquirrel({
            name: 'Operator',
        }),
        new MakerZIP({}, ['darwin']),
        new MakerRpm({
            options: {
                bin: 'Operator',
            },
        }),
        new MakerDeb({
            options: {
                bin: 'Operator',
            },
        }),
        // new MakerFlatpak({
        //   // @ts-ignore
        //   options: {
        //     bin: 'Operator',
        //     id: 'com.helveticascenario.operator',
        //   },
        // }),
    ],
    publishers: [
        new PublisherGithub({
            repository: {
                owner: 'HelveticaScenario',
                name: 'operator',
            },
            prerelease: false,
            draft: false,
        }),
    ],
    plugins: [
        new AutoUnpackNativesPlugin({}),
        new VitePlugin({
            // `build` can specify multiple entry points for the main process
            build: [
                {
                    entry: 'src/main/main.ts',
                    config: 'vite.main.config.ts',
                    target: 'main',
                },
                {
                    entry: 'src/preload/preload.ts',
                    config: 'vite.preload.config.ts',
                    target: 'preload',
                },
            ],
            renderer: [
                {
                    name: 'main_window',
                    config: 'vite.renderer.config.ts',
                },
            ],
        }),
        // Fuses are used to enable/disable various Electron functionality
        // at package time, before code signing the application
        new FusesPlugin({
            version: FuseVersion.V1,
            [FuseV1Options.RunAsNode]: false,
            [FuseV1Options.EnableCookieEncryption]: true,
            [FuseV1Options.EnableNodeOptionsEnvironmentVariable]: false,
            [FuseV1Options.EnableNodeCliInspectArguments]: false,
            [FuseV1Options.EnableEmbeddedAsarIntegrityValidation]: true,
            [FuseV1Options.OnlyLoadAppFromAsar]: true,
        }),
    ],
};

export default config;
