//! Strudel parity regression for `combine_sp`.
//!
//! For every (lhs, rhs, op, mode) row in the strudel-generated fixture
//! at `crates/modular_core/src/pattern_system/__fixtures__/sp_combine.json`,
//! parse the two source strings into `Pattern<IntervalValue>`, combine
//! with the matching alignment mode + arithmetic op, query the first
//! cycle, and assert the produced haps match strudel hap-for-hap on
//! `(whole, part, value)`.
//!
//! The fixture is regenerated by `scripts/gen-sp-fixture.mjs` against
//! the real `@strudel/core` + `@strudel/mini` JS packages.
//!
//! `IntervalValue::Rest` haps emitted by Operator are filtered before
//! comparison — strudel's mini-notation does not emit gap haps for
//! euclidean / degrade / rest constructs, so the structural mismatch is
//! by design.

use std::fs;
use std::path::PathBuf;

use modular_core::dsp::seq::IntervalValue;
use modular_core::pattern_system::sp_combine::{SpAlignmentMode, combine_sp};
use modular_core::pattern_system::{Fraction, Pattern, mini};
use serde::Deserialize;

fn add_iv(a: &IntervalValue, b: &IntervalValue) -> IntervalValue {
    match (a.degree(), b.degree()) {
        (Some(da), Some(db)) => IntervalValue::Degree(da + db),
        _ => IntervalValue::Rest,
    }
}

fn sub_iv(a: &IntervalValue, b: &IntervalValue) -> IntervalValue {
    match (a.degree(), b.degree()) {
        (Some(da), Some(db)) => IntervalValue::Degree(da - db),
        _ => IntervalValue::Rest,
    }
}

#[derive(Debug, Deserialize)]
struct Row {
    lhs: String,
    lhs_source: String,
    rhs: String,
    rhs_source: String,
    op: String,
    mode: String,
    #[serde(default)]
    haps: Option<Vec<FixtureHap>>,
    #[serde(default)]
    error: Option<String>,
}

#[derive(Debug, Deserialize)]
struct FixtureHap {
    whole: Option<[[i64; 2]; 2]>,
    part: [[i64; 2]; 2],
    value: f64,
}

/// Normalized hap shape for comparison.
type CmpHap = (Option<[[i64; 2]; 2]>, [[i64; 2]; 2], i32);

fn parse_mode(s: &str) -> SpAlignmentMode {
    match s {
        "in" => SpAlignmentMode::In,
        "out" => SpAlignmentMode::Out,
        "mix" => SpAlignmentMode::Mix,
        "squeeze" => SpAlignmentMode::Squeeze,
        "squeezeout" => SpAlignmentMode::SqueezeOut,
        "reset" => SpAlignmentMode::Reset,
        "restart" => SpAlignmentMode::Restart,
        other => panic!("unknown mode: {other}"),
    }
}

fn parse_pattern(source: &str) -> Pattern<IntervalValue> {
    let ast = mini::parse_ast(source)
        .unwrap_or_else(|e| panic!("parse error for `{source}`: {e:?}"));
    mini::convert::<IntervalValue>(&ast)
        .unwrap_or_else(|e| panic!("convert error for `{source}`: {e:?}"))
}

fn frac_pair(f: &Fraction) -> [i64; 2] {
    [f.numer(), f.denom()]
}

fn sort_key(h: &CmpHap) -> ([[i64; 2]; 2], i32, Option<[[i64; 2]; 2]>) {
    (h.1, h.2, h.0)
}

#[test]
fn combine_sp_matches_strudel_for_full_grammar_cross() {
    let path: PathBuf = [
        env!("CARGO_MANIFEST_DIR"),
        "src",
        "pattern_system",
        "__fixtures__",
        "sp_combine.json",
    ]
    .iter()
    .collect();
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("missing fixture at {path:?}: {e}"));
    let rows: Vec<Row> =
        serde_json::from_str(&text).expect("fixture must parse as Row[]");
    assert!(!rows.is_empty(), "fixture must contain rows");

    let mut failures: Vec<String> = Vec::new();
    let mut compared = 0usize;

    for row in &rows {
        if row.error.is_some() {
            continue;
        }
        let Some(expected) = row.haps.as_ref() else {
            continue;
        };
        let mode = parse_mode(&row.mode);
        let lhs = parse_pattern(&row.lhs_source);
        let rhs = parse_pattern(&row.rhs_source);
        let combined: Pattern<IntervalValue> = match row.op.as_str() {
            "add" => combine_sp(&lhs, &rhs, mode, add_iv),
            "sub" => combine_sp(&lhs, &rhs, mode, sub_iv),
            other => panic!("unknown op: {other}"),
        };
        let haps =
            combined.query_arc(Fraction::from_integer(0), Fraction::from_integer(1));

        // Filter Rest — strudel emits no gap haps. Compare on
        // (whole, part, value) hap-for-hap as a multiset.
        let mut actual: Vec<CmpHap> = haps
            .iter()
            .filter_map(|h| {
                let d = h.value.degree()?;
                let whole = h
                    .whole
                    .as_ref()
                    .map(|w| [frac_pair(&w.begin), frac_pair(&w.end)]);
                let part = [frac_pair(&h.part.begin), frac_pair(&h.part.end)];
                Some((whole, part, d))
            })
            .collect();

        let mut expected_cmp: Vec<CmpHap> = expected
            .iter()
            .map(|h| (h.whole, h.part, h.value as i32))
            .collect();

        actual.sort_by(|a, b| sort_key(a).cmp(&sort_key(b)));
        expected_cmp.sort_by(|a, b| sort_key(a).cmp(&sort_key(b)));

        compared += 1;
        if actual != expected_cmp {
            failures.push(format!(
                "DIVERGENCE: {lhs}({lhs_src:?}) op={op} mode={mode_s} rhs={rhs}({rhs_src:?})\n  expected ({el}): {exp:?}\n  actual   ({al}): {act:?}",
                lhs = row.lhs,
                lhs_src = row.lhs_source,
                rhs = row.rhs,
                rhs_src = row.rhs_source,
                op = row.op,
                mode_s = row.mode,
                el = expected_cmp.len(),
                al = actual.len(),
                exp = expected_cmp,
                act = actual,
            ));
            if failures.len() >= 25 {
                break;
            }
        }
    }

    if !failures.is_empty() {
        panic!(
            "{n} of {total} rows diverged from strudel (first {shown}):\n{joined}",
            n = failures.len(),
            total = compared,
            shown = failures.len(),
            joined = failures.join("\n\n"),
        );
    }

    // Sanity: 10 LHS cases × 10 RHS cases × 2 ops × 7 modes = 1400 rows.
    // Falling far short of that means the fixture was truncated or row
    // filtering started swallowing live data — fail loudly either way.
    assert!(
        compared >= 1400,
        "expected at least 1400 strudel parity rows, only ran {compared}"
    );
}
